name: Install poetry

runs:
  using: "composite"
  steps:
    - name: Install poetry in Its Own Virtual Environment
      shell: bash
      run: |
        # installing poerty "manually" - see:
        # https://python-poetry.org/docs/#installing-manually
        python3 -m venv venv
        venv/bin/pip install -U pip setuptools
        venv/bin/pip install poetry==2.1.3

    - name: Ensure poetry can be Invoked Outside of its Virtual Environment
      shell: bash
      run: |
        # ensuring poetry is available inside its own environment:
        venv/bin/poetry --version

        # adding poetry's binary from its own environment to the path:
        echo "export PATH=\"\$PATH:$PWD/venv/bin\"" >> ~/.bashrc
        source ~/.bashrc

        echo $PWD
        cat ~/.bashrc
        echo $PATH

        # ensuring poetry is available outside its environemnt:
        poetry --version

