name: Install poetry

runs:
  using: "composite"
  steps:
    - name: Install poetry in Its Own Virtual Environment
      shell: bash
      run: |
        # installing poerty "manually" - see:
        # https://python-poetry.org/docs/#installing-manually
        python3 -m venv venv
        venv/bin/pip install -U pip setuptools
        venv/bin/pip install poetry==2.1.3

    - name: Assert poetry Can be Invoked Inside Its Environment
      shell: bash
      run: venv/bin/poetry --version

    - name: Add poetry's Binary to the Path
      shell: bash
      run: echo "$PWD/venv/bin" >> "$GITHUB_PATH"

    - name: Assert poetry Can be Invoked Outside Its Environment
      shell: bash
      run: poetry --version
