# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.3.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    name: Lint Check
    runs-on: ubuntu-24.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4
  
    - name: Install dependencies
      run: |
        # installing uv - see:
        # https://docs.astral.sh/uv/getting-started/installation/
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # installing tox via uv together with the plugin to manage tox
        # environments via uv itself - see:
        # - https://tox.wiki/en/latest/installation.html
        # - https://github.com/tox-dev/tox-uv
        uv tool install tox --with tox-uv

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-24.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # installing uv - see:
        # https://docs.astral.sh/uv/getting-started/installation/
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # installing tox via uv together with the plugin to manage tox
        # environments via uv itself - see:
        # - https://tox.wiki/en/latest/installation.html
        # - https://github.com/tox-dev/tox-uv
        uv tool install tox --with tox-uv

    - name: Run unit tests
      run: tox -e unit

  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@feat/tox-uv-support
    with:
      charm-path: .
      tox-uv: true

  integration:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    steps:
    - name: Maximise GH runner space
      uses: easimon/maximize-build-space@v7
      with:
        root-reserve-mb: 29696
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        juju-channel: 3.6/stable
        provider: microk8s
        channel: 1.32-strict/stable
        microk8s-addons: "dns hostpath-storage rbac metallb:10.64.140.43-10.64.140.49"
        charmcraft-channel: 3.x/stable

    - name: Install dependencies
      run: |
        # installing uv - see:
        # https://docs.astral.sh/uv/getting-started/installation/
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # installing tox via uv together with the plugin to manage tox
        # environments via uv itself - see:
        # - https://tox.wiki/en/latest/installation.html
        # - https://github.com/tox-dev/tox-uv
        uv tool install tox --with tox-uv
  
        # making sure the specific tox managed by uv is used and not the one
        # inherited from the previus GitHub action step:
        pip uninstall -y tox
        uv tool update-shell

    # Running with kubeflow model because of upstream issue https://github.com/kubeflow/kubeflow/issues/7283
    - name: Run integration tests
      run: tox -vve integration -- --model kubeflow

    # On failure, capture debugging resources      
    - name: Get all
      run: kubectl get all -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get workload logs
      run: kubectl logs --tail 100 -ntesting -lapp.kubernetes.io/name=mlflow-server
      if: failure()

    - name: Get operator logs
      run: kubectl logs --tail 100 -ntesting -loperator.juju.is/name=mlflow-server
      if: failure()
