name: TICS run self-hosted test (github-action)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 2 * * 6" # Every Saturday 2:00 AM UTC

jobs:
  build:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]

    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # installing uv - see:
          # https://docs.astral.sh/uv/getting-started/installation/
          curl -LsSf https://astral.sh/uv/install.sh | sh

          # installing tox via uv together with the plugin to manage tox
          # environments via uv itself - see:
          # - https://tox.wiki/en/latest/installation.html
          # - https://github.com/tox-dev/tox-uv
          uv tool install tox --with tox-uv

      - name: Run tox tests to create coverage.xml
        run: tox run -e unit

      - name: move results to necessary folder for TICS
        run: |
          mkdir cover
          mv coverage.xml cover/coverage.xml

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: pvcviewer-operator
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true